//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace Get_Items
{
}

namespace Get_Items
{
}

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RECORDS {
    
    private RECORDSRECORD[] RECORDField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("RECORD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RECORDSRECORD[] RECORD {
        get {
            return this.RECORDField;
        }
        set {
            this.RECORDField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RECORDSRECORD {
    
    private string entryField;
    
    private int classField;
    
    private int subclassField;
    
    private string nameField;
    
    private int displayidField;
    
    private int qualityField;
    
    private string flagsField;
    
    private string buyCountField;
    
    private string buyPriceField;
    
    private string sellPriceField;
    
    private int inventoryTypeField;
    
    private string allowableClassField;
    
    private string allowableRaceField;
    
    private string itemLevelField;
    
    private string requiredLevelField;
    
    private string requiredSkillField;
    
    private string requiredSkillRankField;
    
    private string requiredspellField;
    
    private string requiredhonorrankField;
    
    private string requiredCityRankField;
    
    private string requiredReputationFactionField;
    
    private string requiredReputationRankField;
    
    private string maxcountField;
    
    private string stackableField;
    
    private string containerSlotsField;
    
    private string stat_type1Field;
    
    private string stat_value1Field;
    
    private string stat_type2Field;
    
    private string stat_value2Field;
    
    private string stat_type3Field;
    
    private string stat_value3Field;
    
    private string stat_type4Field;
    
    private string stat_value4Field;
    
    private string stat_type5Field;
    
    private string stat_value5Field;
    
    private string stat_type6Field;
    
    private string stat_value6Field;
    
    private string stat_type7Field;
    
    private string stat_value7Field;
    
    private string stat_type8Field;
    
    private string stat_value8Field;
    
    private string stat_type9Field;
    
    private string stat_value9Field;
    
    private string stat_type10Field;
    
    private string stat_value10Field;
    
    private string dmg_min1Field;
    
    private string dmg_max1Field;
    
    private string dmg_type1Field;
    
    private string dmg_min2Field;
    
    private string dmg_max2Field;
    
    private string dmg_type2Field;
    
    private string dmg_min3Field;
    
    private string dmg_max3Field;
    
    private string dmg_type3Field;
    
    private string dmg_min4Field;
    
    private string dmg_max4Field;
    
    private string dmg_type4Field;
    
    private string dmg_min5Field;
    
    private string dmg_max5Field;
    
    private string dmg_type5Field;
    
    private string armorField;
    
    private string holy_resField;
    
    private string fire_resField;
    
    private string nature_resField;
    
    private string frost_resField;
    
    private string shadow_resField;
    
    private string arcane_resField;
    
    private string delayField;
    
    private string ammo_typeField;
    
    private string rangedModRangeField;
    
    private string spellid_1Field;
    
    private string spelltrigger_1Field;
    
    private string spellcharges_1Field;
    
    private string spellppmRate_1Field;
    
    private string spellcooldown_1Field;
    
    private string spellcategory_1Field;
    
    private string spellcategorycooldown_1Field;
    
    private string spellid_2Field;
    
    private string spelltrigger_2Field;
    
    private string spellcharges_2Field;
    
    private string spellppmRate_2Field;
    
    private string spellcooldown_2Field;
    
    private string spellcategory_2Field;
    
    private string spellcategorycooldown_2Field;
    
    private string spellid_3Field;
    
    private string spelltrigger_3Field;
    
    private string spellcharges_3Field;
    
    private string spellppmRate_3Field;
    
    private string spellcooldown_3Field;
    
    private string spellcategory_3Field;
    
    private string spellcategorycooldown_3Field;
    
    private string spellid_4Field;
    
    private string spelltrigger_4Field;
    
    private string spellcharges_4Field;
    
    private string spellppmRate_4Field;
    
    private string spellcooldown_4Field;
    
    private string spellcategory_4Field;
    
    private string spellcategorycooldown_4Field;
    
    private string spellid_5Field;
    
    private string spelltrigger_5Field;
    
    private string spellcharges_5Field;
    
    private string spellppmRate_5Field;
    
    private string spellcooldown_5Field;
    
    private string spellcategory_5Field;
    
    private string spellcategorycooldown_5Field;
    
    private string bondingField;
    
    private string descriptionField;
    
    private string pageTextField;
    
    private string languageIDField;
    
    private string pageMaterialField;
    
    private string startquestField;
    
    private string lockidField;
    
    private string materialField;
    
    private string sheathField;
    
    private string randomPropertyField;
    
    private string blockField;
    
    private string itemsetField;
    
    private string maxDurabilityField;
    
    private string areaField;
    
    private string mapField;
    
    private string bagFamilyField;
    
    private string scriptNameField;
    
    private string disenchantIDField;
    
    private string foodTypeField;
    
    private string minMoneyLootField;
    
    private string maxMoneyLootField;
    
    private string durationField;
    
    private string extraFlagsField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string entry {
        get {
            return this.entryField;
        }
        set {
            this.entryField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int subclass {
        get {
            return this.subclassField;
        }
        set {
            this.subclassField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int displayid {
        get {
            return this.displayidField;
        }
        set {
            this.displayidField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Quality {
        get {
            return this.qualityField;
        }
        set {
            this.qualityField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Flags {
        get {
            return this.flagsField;
        }
        set {
            this.flagsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BuyCount {
        get {
            return this.buyCountField;
        }
        set {
            this.buyCountField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BuyPrice {
        get {
            return this.buyPriceField;
        }
        set {
            this.buyPriceField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SellPrice {
        get {
            return this.sellPriceField;
        }
        set {
            this.sellPriceField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int InventoryType {
        get {
            return this.inventoryTypeField;
        }
        set {
            this.inventoryTypeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AllowableClass {
        get {
            return this.allowableClassField;
        }
        set {
            this.allowableClassField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AllowableRace {
        get {
            return this.allowableRaceField;
        }
        set {
            this.allowableRaceField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ItemLevel {
        get {
            return this.itemLevelField;
        }
        set {
            this.itemLevelField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequiredLevel {
        get {
            return this.requiredLevelField;
        }
        set {
            this.requiredLevelField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequiredSkill {
        get {
            return this.requiredSkillField;
        }
        set {
            this.requiredSkillField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequiredSkillRank {
        get {
            return this.requiredSkillRankField;
        }
        set {
            this.requiredSkillRankField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string requiredspell {
        get {
            return this.requiredspellField;
        }
        set {
            this.requiredspellField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string requiredhonorrank {
        get {
            return this.requiredhonorrankField;
        }
        set {
            this.requiredhonorrankField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequiredCityRank {
        get {
            return this.requiredCityRankField;
        }
        set {
            this.requiredCityRankField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequiredReputationFaction {
        get {
            return this.requiredReputationFactionField;
        }
        set {
            this.requiredReputationFactionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RequiredReputationRank {
        get {
            return this.requiredReputationRankField;
        }
        set {
            this.requiredReputationRankField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string maxcount {
        get {
            return this.maxcountField;
        }
        set {
            this.maxcountField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stackable {
        get {
            return this.stackableField;
        }
        set {
            this.stackableField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ContainerSlots {
        get {
            return this.containerSlotsField;
        }
        set {
            this.containerSlotsField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type1 {
        get {
            return this.stat_type1Field;
        }
        set {
            this.stat_type1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value1 {
        get {
            return this.stat_value1Field;
        }
        set {
            this.stat_value1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type2 {
        get {
            return this.stat_type2Field;
        }
        set {
            this.stat_type2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value2 {
        get {
            return this.stat_value2Field;
        }
        set {
            this.stat_value2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type3 {
        get {
            return this.stat_type3Field;
        }
        set {
            this.stat_type3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value3 {
        get {
            return this.stat_value3Field;
        }
        set {
            this.stat_value3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type4 {
        get {
            return this.stat_type4Field;
        }
        set {
            this.stat_type4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value4 {
        get {
            return this.stat_value4Field;
        }
        set {
            this.stat_value4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type5 {
        get {
            return this.stat_type5Field;
        }
        set {
            this.stat_type5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value5 {
        get {
            return this.stat_value5Field;
        }
        set {
            this.stat_value5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type6 {
        get {
            return this.stat_type6Field;
        }
        set {
            this.stat_type6Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value6 {
        get {
            return this.stat_value6Field;
        }
        set {
            this.stat_value6Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type7 {
        get {
            return this.stat_type7Field;
        }
        set {
            this.stat_type7Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value7 {
        get {
            return this.stat_value7Field;
        }
        set {
            this.stat_value7Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type8 {
        get {
            return this.stat_type8Field;
        }
        set {
            this.stat_type8Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value8 {
        get {
            return this.stat_value8Field;
        }
        set {
            this.stat_value8Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type9 {
        get {
            return this.stat_type9Field;
        }
        set {
            this.stat_type9Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value9 {
        get {
            return this.stat_value9Field;
        }
        set {
            this.stat_value9Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_type10 {
        get {
            return this.stat_type10Field;
        }
        set {
            this.stat_type10Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stat_value10 {
        get {
            return this.stat_value10Field;
        }
        set {
            this.stat_value10Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_min1 {
        get {
            return this.dmg_min1Field;
        }
        set {
            this.dmg_min1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_max1 {
        get {
            return this.dmg_max1Field;
        }
        set {
            this.dmg_max1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_type1 {
        get {
            return this.dmg_type1Field;
        }
        set {
            this.dmg_type1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_min2 {
        get {
            return this.dmg_min2Field;
        }
        set {
            this.dmg_min2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_max2 {
        get {
            return this.dmg_max2Field;
        }
        set {
            this.dmg_max2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_type2 {
        get {
            return this.dmg_type2Field;
        }
        set {
            this.dmg_type2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_min3 {
        get {
            return this.dmg_min3Field;
        }
        set {
            this.dmg_min3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_max3 {
        get {
            return this.dmg_max3Field;
        }
        set {
            this.dmg_max3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_type3 {
        get {
            return this.dmg_type3Field;
        }
        set {
            this.dmg_type3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_min4 {
        get {
            return this.dmg_min4Field;
        }
        set {
            this.dmg_min4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_max4 {
        get {
            return this.dmg_max4Field;
        }
        set {
            this.dmg_max4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_type4 {
        get {
            return this.dmg_type4Field;
        }
        set {
            this.dmg_type4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_min5 {
        get {
            return this.dmg_min5Field;
        }
        set {
            this.dmg_min5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_max5 {
        get {
            return this.dmg_max5Field;
        }
        set {
            this.dmg_max5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dmg_type5 {
        get {
            return this.dmg_type5Field;
        }
        set {
            this.dmg_type5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string armor {
        get {
            return this.armorField;
        }
        set {
            this.armorField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string holy_res {
        get {
            return this.holy_resField;
        }
        set {
            this.holy_resField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fire_res {
        get {
            return this.fire_resField;
        }
        set {
            this.fire_resField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nature_res {
        get {
            return this.nature_resField;
        }
        set {
            this.nature_resField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string frost_res {
        get {
            return this.frost_resField;
        }
        set {
            this.frost_resField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string shadow_res {
        get {
            return this.shadow_resField;
        }
        set {
            this.shadow_resField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arcane_res {
        get {
            return this.arcane_resField;
        }
        set {
            this.arcane_resField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string delay {
        get {
            return this.delayField;
        }
        set {
            this.delayField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ammo_type {
        get {
            return this.ammo_typeField;
        }
        set {
            this.ammo_typeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RangedModRange {
        get {
            return this.rangedModRangeField;
        }
        set {
            this.rangedModRangeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellid_1 {
        get {
            return this.spellid_1Field;
        }
        set {
            this.spellid_1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spelltrigger_1 {
        get {
            return this.spelltrigger_1Field;
        }
        set {
            this.spelltrigger_1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcharges_1 {
        get {
            return this.spellcharges_1Field;
        }
        set {
            this.spellcharges_1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellppmRate_1 {
        get {
            return this.spellppmRate_1Field;
        }
        set {
            this.spellppmRate_1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcooldown_1 {
        get {
            return this.spellcooldown_1Field;
        }
        set {
            this.spellcooldown_1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategory_1 {
        get {
            return this.spellcategory_1Field;
        }
        set {
            this.spellcategory_1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategorycooldown_1 {
        get {
            return this.spellcategorycooldown_1Field;
        }
        set {
            this.spellcategorycooldown_1Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellid_2 {
        get {
            return this.spellid_2Field;
        }
        set {
            this.spellid_2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spelltrigger_2 {
        get {
            return this.spelltrigger_2Field;
        }
        set {
            this.spelltrigger_2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcharges_2 {
        get {
            return this.spellcharges_2Field;
        }
        set {
            this.spellcharges_2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellppmRate_2 {
        get {
            return this.spellppmRate_2Field;
        }
        set {
            this.spellppmRate_2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcooldown_2 {
        get {
            return this.spellcooldown_2Field;
        }
        set {
            this.spellcooldown_2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategory_2 {
        get {
            return this.spellcategory_2Field;
        }
        set {
            this.spellcategory_2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategorycooldown_2 {
        get {
            return this.spellcategorycooldown_2Field;
        }
        set {
            this.spellcategorycooldown_2Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellid_3 {
        get {
            return this.spellid_3Field;
        }
        set {
            this.spellid_3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spelltrigger_3 {
        get {
            return this.spelltrigger_3Field;
        }
        set {
            this.spelltrigger_3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcharges_3 {
        get {
            return this.spellcharges_3Field;
        }
        set {
            this.spellcharges_3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellppmRate_3 {
        get {
            return this.spellppmRate_3Field;
        }
        set {
            this.spellppmRate_3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcooldown_3 {
        get {
            return this.spellcooldown_3Field;
        }
        set {
            this.spellcooldown_3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategory_3 {
        get {
            return this.spellcategory_3Field;
        }
        set {
            this.spellcategory_3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategorycooldown_3 {
        get {
            return this.spellcategorycooldown_3Field;
        }
        set {
            this.spellcategorycooldown_3Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellid_4 {
        get {
            return this.spellid_4Field;
        }
        set {
            this.spellid_4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spelltrigger_4 {
        get {
            return this.spelltrigger_4Field;
        }
        set {
            this.spelltrigger_4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcharges_4 {
        get {
            return this.spellcharges_4Field;
        }
        set {
            this.spellcharges_4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellppmRate_4 {
        get {
            return this.spellppmRate_4Field;
        }
        set {
            this.spellppmRate_4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcooldown_4 {
        get {
            return this.spellcooldown_4Field;
        }
        set {
            this.spellcooldown_4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategory_4 {
        get {
            return this.spellcategory_4Field;
        }
        set {
            this.spellcategory_4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategorycooldown_4 {
        get {
            return this.spellcategorycooldown_4Field;
        }
        set {
            this.spellcategorycooldown_4Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellid_5 {
        get {
            return this.spellid_5Field;
        }
        set {
            this.spellid_5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spelltrigger_5 {
        get {
            return this.spelltrigger_5Field;
        }
        set {
            this.spelltrigger_5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcharges_5 {
        get {
            return this.spellcharges_5Field;
        }
        set {
            this.spellcharges_5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellppmRate_5 {
        get {
            return this.spellppmRate_5Field;
        }
        set {
            this.spellppmRate_5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcooldown_5 {
        get {
            return this.spellcooldown_5Field;
        }
        set {
            this.spellcooldown_5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategory_5 {
        get {
            return this.spellcategory_5Field;
        }
        set {
            this.spellcategory_5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string spellcategorycooldown_5 {
        get {
            return this.spellcategorycooldown_5Field;
        }
        set {
            this.spellcategorycooldown_5Field = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bonding {
        get {
            return this.bondingField;
        }
        set {
            this.bondingField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PageText {
        get {
            return this.pageTextField;
        }
        set {
            this.pageTextField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LanguageID {
        get {
            return this.languageIDField;
        }
        set {
            this.languageIDField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PageMaterial {
        get {
            return this.pageMaterialField;
        }
        set {
            this.pageMaterialField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string startquest {
        get {
            return this.startquestField;
        }
        set {
            this.startquestField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lockid {
        get {
            return this.lockidField;
        }
        set {
            this.lockidField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Material {
        get {
            return this.materialField;
        }
        set {
            this.materialField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sheath {
        get {
            return this.sheathField;
        }
        set {
            this.sheathField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RandomProperty {
        get {
            return this.randomPropertyField;
        }
        set {
            this.randomPropertyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string block {
        get {
            return this.blockField;
        }
        set {
            this.blockField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string itemset {
        get {
            return this.itemsetField;
        }
        set {
            this.itemsetField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MaxDurability {
        get {
            return this.maxDurabilityField;
        }
        set {
            this.maxDurabilityField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Map {
        get {
            return this.mapField;
        }
        set {
            this.mapField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BagFamily {
        get {
            return this.bagFamilyField;
        }
        set {
            this.bagFamilyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ScriptName {
        get {
            return this.scriptNameField;
        }
        set {
            this.scriptNameField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DisenchantID {
        get {
            return this.disenchantIDField;
        }
        set {
            this.disenchantIDField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FoodType {
        get {
            return this.foodTypeField;
        }
        set {
            this.foodTypeField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string minMoneyLoot {
        get {
            return this.minMoneyLootField;
        }
        set {
            this.minMoneyLootField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string maxMoneyLoot {
        get {
            return this.maxMoneyLootField;
        }
        set {
            this.maxMoneyLootField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExtraFlags {
        get {
            return this.extraFlagsField;
        }
        set {
            this.extraFlagsField = value;
        }
    }
}
